### ISSUE TITLE
Cleanup variable_* functions

### ISSUE THREAD

**Issue by alexfinnarn** [alexfinnarn/xmlsitemap#3]
The variable_\* functions are deprecated in Backdrop and need to be changed to how Backdrop handles declaring variables.

**Comment by jenlampton** [comment]
Backdrop uses a single configuration file to hold all the variables for a module. We'll need to define and create that file so that it's loaded at install time, then simply change all the function calls to config_get/set instead.

**Comment by jenlampton** [comment]
Well, it took all day, but https://github.com/alexfinnarn/backdrop-xml-sitemap/pull/19

**Comment by alexfinnarn** [comment]
I can take a look at this, but the sitemap didn't generate for me after switching to the branch. No more indication of the specific error was included the error message so I don't have any more info at this time.

**Comment by jenlampton** [comment]
I ran into that too. You'll need to flush all caches and run cron, IIRC.

**Comment by alexfinnarn** [comment]
Well, that was a humdinger of a PR. Thanks again @jenlampton!
